spring.application.name=WEB
spring.data.mongodb.uri = mongodb+srv://root:1234567890@web.xwnqlgu.mongodb.net/
spring.data.mongodb.database=Web
server.port=8092
server.error.whitelabel.enabled=false
server.error.path=/error
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=275fructose2025@gmail.com
spring.mail.password=efrc qcuk xqqg wvag
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# application.properties

# 1. SECRET KEY (Ph?i là m?t chu?i Base64 dài)
application.security.jwt.secret-key=+epjP6E6qb9awiEeB2bnjBDcCk/Y7fZl0Wbxrow3QHI=i

# 2. ACCESS TOKEN EXPIRATION (Ph?i là s? nguyên TÍNH B?NG MILLISECONDS)
# ??m b?o không có ký t? nào khác trên dòng này.
application.security.jwt.expiration=86400000 

# 3. REFRESH TOKEN EXPIRATION (Ph?i là s? nguyên TÍNH B?NG MILLISECONDS)
application.security.jwt.refresh-token.expiration=604800000
logging.level.org.springframework.security=DEBUG
logging.level.hcmute.edu.vn.web.Config=DEBUG
